#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

#include "constants/pokemon_config.h"
// National Pokedex order.
// These constants are NOT disabled by P_GEN_X_POKEMON to keep pokedex_orders.h clean.
enum {
    NATIONAL_DEX_NONE,
    NATIONAL_DEX_BULBASAUR,
};

#if P_GEN_8_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BULBASAUR
#elif P_GEN_7_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BULBASAUR
#elif P_GEN_6_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BULBASAUR
#elif P_GEN_5_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BULBASAUR
#elif P_GEN_4_POKEMON == TRUE
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BULBASAUR
#else
    #define NATIONAL_DEX_COUNT  NATIONAL_DEX_BULBASAUR
#endif

#define POKEMON_SLOTS_NUMBER (NATIONAL_DEX_COUNT + 1)

// Hoenn Pokedex order
enum {
    HOENN_DEX_NONE,
    HOENN_DEX_BULBASAUR,
};

#define HOENN_DEX_COUNT (HOENN_DEX_BULBASAUR + 1)

#endif // GUARD_CONSTANTS_POKEDEX_H
